#!/bin/bash

sudo swapon --show
sudo fallocate -l 4G /swapfile
sudo dd if=/dev/zero of=/swapfile bs=1MiB count=4096
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
sudo swapon --show

