#!/bin/bash

# install build tools
apt-get install -y build-essential

# download latest lts nodejs, compile and install
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
apt-get install -y nodejs
