#!/bin/bash
NAME=$1
if [[ ! $NAME ]];then
  NAME='laravel-app'
fi
git clone https://github.com/laravel/laravel.git $NAME
cd $NAME
# docker run --rm -v $(pwd):/app composer install
mv .env.example .env
sudo apt update
sudo apt install php-xml php-curl
composer install
sudo chown -R $USER:$USER ../$NAME
sudo chown -R $USER:www-data storage
sudo chown -R $USER:www-data bootstrap/cache
chmod 777 -R storage bootstrap/cache
php artisan key:generate
cd ..
